### ISSUE TITLE
Panic "interface is nil"

### ISSUE THREAD

**Issue by engel75** [lovoo/xenstats_exporter#5]
Hi,

I get the following error starting the exporter:

`./xenstats_exporter `  
```
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x95cd00, 0xc82021ab00)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
main.Xenstats.createPoolMetrics(0xc820011fc0, 0xc820016ba0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/engel/GO/src/github.com/lovoo/xenstats_exporter/xenstats.go:247 +0x48b
main.(*Exporter).collect(0xc820016b40)
	/home/engel/GO/src/github.com/lovoo/xenstats_exporter/collector.go:68 +0x1eb
main.NewExporter(0xc8201402d0, 0xa, 0xc820140318, 0x4, 0xc820140340, 0xb, 0x0)
	/home/engel/GO/src/github.com/lovoo/xenstats_exporter/collector.go:37 +0x11a
main.main()
	/home/engel/GO/src/github.com/lovoo/xenstats_exporter/main.go:45 +0x1a0
```

Did I miss something?

**Comment by engel75** [comment]
Looks like this is Xenserver 7.0 related.

**Comment by engel75** [comment]
```
(gdb) n
247			haEnabledMetric, err := s.createMetric("pool_ha_enabled", "true if HA is enabled on the pool, false otherwise", "bool", "pool", nameLabel.(string), float64(haEnabledInt))
(gdb) n
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x81f680, 0xc42027cfc0)
	/home/engel/GO/go/src/runtime/panic.go:500 +0x1a1
main.Xenstats.createPoolMetrics(0xc42012a940, 0xc42016e9c0, 0xc42000db90, 0x2, 0x2, 0x0, 0x0)
	/home/engel/GO/src/github.com/lovoo/xenstats_exporter/xenstats.go:247 +0x20a
main.(*Exporter).collect(0xc42016e960)
	/home/engel/GO/src/github.com/lovoo/xenstats_exporter/collector.go:68 +0x119
main.NewExporter(0xc420128e20, 0xa, 0xc420128e68, 0x4, 0xc420128e90, 0xb, 0x0)
	/home/engel/GO/src/github.com/lovoo/xenstats_exporter/collector.go:37 +0xe6
main.main()
	/home/engel/GO/src/github.com/lovoo/xenstats_exporter/main.go:44 +0x115
[Thread 0x7ffff5fed700 (LWP 19127) exited]
warning: Error removing breakpoint 0
warning: Error removing breakpoint 0
warning: Error removing breakpoint 0
warning: Error removing breakpoint 0
warning: Error removing breakpoint 0
[Thread 0x7ffff67ee700 (LWP 19126) exited]
[Thread 0x7ffff6fef700 (LWP 19125) exited]
[Thread 0x7ffff7fc0700 (LWP 19123) exited]
[Inferior 1 (process 19123) exited with code 02]
```

**Comment by SqiSch** [comment]
Hei Engel, 

thank you for the issue. 
can you please fix it and create a pull request for that?
I´m not able to fix/test it at the moment.

Marcel

**Comment by svarco** [comment]
This error happens, when no name is set for the Xen cluster and therefore the `get_name_label` API-Call returns a null-value and isn't directly a bug in the code of xenstats_exporter.

To fix the problem, open XenCenter, connect to the xen host, right click on it and choose: "Create Pool". Set a name.
After this `get_name_label` will return this name and xenstats_exporter runs fine.

However, what I discovered was that in the code of xenstats_exporter in file: **xenstats.go, _line: 240_** there is no check for the name_label value:
```go
nameLabel, err := s.xend.GetSpecificValue("pool.get_name_label", elem.Ref)
```

As in all the subsequent calls there is a check like:
```go
if err != nil {
  return metrics, fmt.Errorf("XEN Api Error: %v", err)
}
```
this should probably also be done for nameLabel. However, I do not know whether this was left out by purpose or not.
