### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by eccoilmoro** [lovoo/xenstats_exporter#8]
Starting the exporter the following error is raised , i'm logging in using the admin account of xenserver.
./xenstats_exporter -config.file ../config.yml
2019/03/20 09:26:02 service.time call error: Invalid credentials supplied
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7a7bb7]

goroutine 1 [running]:
github.com/xenserver/go-xenserver-client.(*XenAPIClient).APICall(0x0, 0xc0000c7bc0, 0x97731e, 0xc, 0x0, 0x0, 0x0, 0x4a, 0x50)
        /root/go/src/github.com/xenserver/go-xenserver-client/client.go:58 +0x37
github.com/xenserver/go-xenserver-client.(*XenAPIClient).GetHosts(0x0, 0x4a, 0x997ee8, 0xc0000ca460, 0xc0000c7c38, 0xc0000c7cd8)
        /root/go/src/github.com/xenserver/go-xenserver-client/client.go:95 +0xb0
main.Xenstats.createHostMemMetrics(0xc00002fb00, 0x0, 0xc0000247f0, 0x4, 0xc000024800, 0x9, 0xc000067d10)
        /root/go/src/github.com/lovoo/xenstats_exporter/xenstats.go:95 +0x43
main.(*Exporter).collect(0xc00007a540)
        /root/go/src/github.com/lovoo/xenstats_exporter/collector.go:63 +0xa8
main.NewExporter(...)
        /root/go/src/github.com/lovoo/xenstats_exporter/collector.go:37
main.main()
        /root/go/src/github.com/lovoo/xenstats_exporter/main.go:45 +0x1c7

**Comment by eccoilmoro** [comment]
We were trying to run xen_exporter on a slave xenserver, not suitable for XAPI calls.
